### ISSUE TITLE
[Request]: DLSS Swapper

### ISSUE THREAD

**Issue by ALazyMeme** [brian6932/dank-scoop#274]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Criteria 1
- [X] Criteria 2
- [X] Criteria 3

### Name

DLSS Swapper

### Description

Swaps DLSS versions in games

### Homepage

https://github.com/beeradmoore/dlss-swapper

### Download Link(s)

https://github.com/beeradmoore/dlss-swapper/releases

### Some Indication of Popularity/Repute

Good software, very popular. Can't see any other buckets that have the package

**Comment by brian6932** [comment]
https://github.com/maokwen/scoop-bucket/blob/master/bucket/dlss-swapper.json
